version: 2
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - checkout
     - run:
         name: 最初の一歩
         command: |
           echo 'Hello World!'
     - run:
         name: コードの取得
         command: |
           ls -al
           echo 'first job!!!'
           pwd
           cat README.md
 test:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: メッセージ出力
         command: |
           ls -al
           echo 'second job!!!'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - hold: # <<< ジョブの続きを実行するには CircleCI の Web ページ上で手動で承認する必要があります。
          type: approval # <<< このキーを使うと Workflow を「待機」状態にします
          requires: # test2 が完了すると hold ジョブに処理が移ります
           - build
      - test:
          requires:
            - hold
          filters:
            branches:
              only: master