version: 2.1

executors:
  my-executor:
    docker:
      - image: buildpack-deps:jessie
    working_directory: /tmp

jobs:
 build:
   docker:
     - image: alpine:3.7
   executor: my-executor
   steps:
     - checkout
     - run:
         name: 最初の一歩
         command: |
           echo 'Hello World!'
     - run: mkdir -p workspace
     - run: echo "Hello, world!" > workspace/echo-output
     - run:
         name: ディレクトリ内容確認
         command: |
           ls -al workspace
           pwd

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
