version: 2

jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: 準備
          command: |
            echo '準備開始!'
      - run:
          name: 作業フォルダ作成
          command: |
            mkdir -p desc
            echo "Hello, world!" > desc/test.txt
            pwd
            ls -lat
      - persist_to_workspace:
          root: /root/project
          paths:
            - desc
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: 作業フォルダを参照
          command: |
            ls -al
      - attach_workspace:
          at: /root/project
      - run: cat /root/project/desc/test.txt
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
