version: 2.1

executors:
  my-linux:
    docker:
      - image: alpine:3.7
    working_directory: /root/project
jobs:
  build:
    executor: my-linux
    steps:
      - run:
        name: 準備
      - checkout
      - run: mkdir -p desc
      - run: echo "Hello, world!" > desc/newfile.txt
      - run: pwd
      - run: ls -lat
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
