version: 2
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
        name: 最初の一歩
        command: |
          echo 'Hello World!'
          echo 'This is the delivery pipeline'
      - run:
        name: buildコードの取得
        command: |
          ls -al
          echo '1JOB実行'
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
        name: testコードの取得
        command: |
          echo '2JOB実行'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test