version: 2
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - checkout
     - run:
         name: 最初の一歩
         command: |
           echo 'Hello World!'
     - run:
         name: コードの取得
         command: |
           ls -al
           echo 'first job!!!'
           pwd
           cat README.md
 test:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: メッセージ出力
         command: |
           ls -al
           echo 'second job!!!'
 nightly-test:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: ナイトリージョブ！！
         command: |
           echo 'nightly-test job!!!'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "30 15 * * *"
          filters:
            branches:
              only: master
    jobs:
      - nightly-test
